"""Domain enums — ADR-001 v1.2 (D-05/10/18/19)."""

from enum import StrEnum


class PartyType(StrEnum):
    PERSON = "PERSON"
    ORGANIZATION = "ORGANIZATION"


class PartyRoleType(StrEnum):
    CLIENT = "CLIENT"
    CONTRACTOR = "CONTRACTOR"
    INSURED = "INSURED"
    OWNER = "OWNER"
    REFERRER = "REFERRER"
    EXECUTIVE = "EXECUTIVE"
    AGENT = "AGENT"


class DataSource(StrEnum):
    MANUAL = "MANUAL"
    EXCEL_IMPORT = "EXCEL_IMPORT"
    SYSTEM_GENERATED = "SYSTEM_GENERATED"
    CARRIER_API = "CARRIER_API"
    FILE = "FILE"
    PORTAL = "PORTAL"


class TermSource(StrEnum):
    SYSTEM_GENERATED = "SYSTEM_GENERATED"
    CARRIER = "CARRIER"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"


class DueDateSource(StrEnum):
    SYSTEM_GENERATED = "SYSTEM_GENERATED"
    CARRIER = "CARRIER"
    MANUAL = "MANUAL"
    IMPORT = "IMPORT"


class SubmissionStatus(StrEnum):
    DRAFT = "DRAFT"
    QUOTING = "QUOTING"
    QUOTED = "QUOTED"
    WAITING_CLIENT = "WAITING_CLIENT"
    ACCEPTED = "ACCEPTED"
    SUBMITTED = "SUBMITTED"
    ISSUING = "ISSUING"
    ISSUED = "ISSUED"
    DECLINED = "DECLINED"
    LOST = "LOST"
    CANCELLED = "CANCELLED"


class PolicyStatus(StrEnum):
    PENDING_EFFECTIVE = "PENDING_EFFECTIVE"
    ACTIVE = "ACTIVE"
    EXPIRING = "EXPIRING"
    EXPIRED = "EXPIRED"
    CANCELLATION_PENDING = "CANCELLATION_PENDING"
    CANCELLED = "CANCELLED"


class RenewalOpportunityStatus(StrEnum):
    UPCOMING = "UPCOMING"
    CONTACT_PENDING = "CONTACT_PENDING"
    CONTACTED = "CONTACTED"
    QUOTING = "QUOTING"
    PROPOSAL_SENT = "PROPOSAL_SENT"
    WAITING_CLIENT = "WAITING_CLIENT"
    ACCEPTED = "ACCEPTED"
    RENEWED = "RENEWED"
    DECLINED = "DECLINED"
    LOST = "LOST"
    NON_RENEWED = "NON_RENEWED"


class CoverageKnowledgeState(StrEnum):
    INSURED_WITH_US = "INSURED_WITH_US"
    KNOWN_EXTERNAL_COVERAGE = "KNOWN_EXTERNAL_COVERAGE"
    NO_COVERAGE_RECORDED = "NO_COVERAGE_RECORDED"
    UNKNOWN = "UNKNOWN"


class CalculationBase(StrEnum):
    NET_PREMIUM = "NET_PREMIUM"
    GROSS_PREMIUM = "GROSS_PREMIUM"
    ANNUAL_PREMIUM = "ANNUAL_PREMIUM"
    COLLECTED_PREMIUM = "COLLECTED_PREMIUM"
    FIXED_AMOUNT = "FIXED_AMOUNT"
    OTHER = "OTHER"


class CarrierCapabilityMode(StrEnum):
    MANUAL = "MANUAL"
    FILE = "FILE"
    API = "API"
    FULL_DIGITAL = "FULL_DIGITAL"


class CarrierCapabilityKind(StrEnum):
    QUOTE = "QUOTE"
    ISSUE = "ISSUE"
    POLICY_INQUIRY = "POLICY_INQUIRY"
    COLLECTIONS = "COLLECTIONS"
    COMMISSION = "COMMISSION"
    DOCUMENTS = "DOCUMENTS"
    CLAIMS = "CLAIMS"


class PaymentPromiseStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FULFILLED = "FULFILLED"
    BROKEN = "BROKEN"
    CANCELLED = "CANCELLED"


class CollectionBand(StrEnum):
    AUTOMATIC = "AUTOMATIC"
    INTERVENTION = "INTERVENTION"
    PROMISE = "PROMISE"
    BROKEN_PROMISE = "BROKEN_PROMISE"
    EXCEPTION = "EXCEPTION"


class ClaimStatus(StrEnum):
    REPORTED = "REPORTED"
    DOCUMENTS_PENDING = "DOCUMENTS_PENDING"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    ADJUSTER_ASSIGNED = "ADJUSTER_ASSIGNED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    SETTLED = "SETTLED"
    CLOSED = "CLOSED"


class RecommendationDecision(StrEnum):
    ACCEPTED = "ACCEPTED"
    DISCARDED = "DISCARDED"
    POSTPONED = "POSTPONED"
