"""ADR-009 — Carrier Incentive Plans constants (not ordinary commissions)."""

from __future__ import annotations

# Plan metric
METRIC_COLLECTION = "COLLECTION"
METRIC_PRODUCTION = "PRODUCTION"
METRIC_TYPES = frozenset({METRIC_COLLECTION, METRIC_PRODUCTION})

# Period
PERIOD_ANNUAL = "ANNUAL"
PERIOD_CUSTOM = "CUSTOM"
PERIOD_TYPES = frozenset({PERIOD_ANNUAL, PERIOD_CUSTOM})

# Plan status
PLAN_DRAFT = "DRAFT"
PLAN_ACTIVE = "ACTIVE"
PLAN_CLOSED = "CLOSED"
PLAN_CANCELLED = "CANCELLED"
PLAN_STATUSES = frozenset({PLAN_DRAFT, PLAN_ACTIVE, PLAN_CLOSED, PLAN_CANCELLED})

# Scope kinds
SCOPE_CARRIER = "CARRIER"  # whole carrier
SCOPE_LINE = "LINE"
SCOPE_PRODUCT = "PRODUCT"
SCOPE_AGENT_CODE = "AGENT_CODE"
SCOPE_KINDS = frozenset({SCOPE_CARRIER, SCOPE_LINE, SCOPE_PRODUCT, SCOPE_AGENT_CODE})

# Benefit
BENEFIT_PERCENTAGE = "PERCENTAGE"
BENEFIT_FIXED = "FIXED_AMOUNT"
BENEFIT_TYPES = frozenset({BENEFIT_PERCENTAGE, BENEFIT_FIXED})

# Calculation base (explicit — never silent)
BASE_COLLECTED_PREMIUM = "COLLECTED_PREMIUM"
BASE_NET_PREMIUM = "NET_PREMIUM"
BASE_TOTAL_PREMIUM = "TOTAL_PREMIUM"
BASE_ISSUED_PRODUCTION = "ISSUED_PRODUCTION"
CALCULATION_BASES = frozenset(
    {
        BASE_COLLECTED_PREMIUM,
        BASE_NET_PREMIUM,
        BASE_TOTAL_PREMIUM,
        BASE_ISSUED_PRODUCTION,
    }
)

# Eligible transaction confirmation (carrier)
TXN_PENDING = "PENDING"
TXN_CONFIRMED = "CONFIRMED"
TXN_REVERSED = "REVERSED"
TXN_STATUSES = frozenset({TXN_PENDING, TXN_CONFIRMED, TXN_REVERSED})

# Benefit lifecycle (progress / accrual — not carrier recognition)
BENEFIT_ESTIMATED = "ESTIMATED"
BENEFIT_EARNED = "EARNED"

# Settlement status
SETTLE_CALCULATED = "CALCULATED"
SETTLE_CLAIMED = "CLAIMED"
SETTLE_RECOGNIZED = "RECOGNIZED"
SETTLE_PAID = "PAID"
SETTLE_DISPUTED = "DISPUTED"
SETTLE_REJECTED = "REJECTED"
SETTLE_PARTIALLY_PAID = "PARTIALLY_PAID"
SETTLEMENT_STATUSES = frozenset(
    {
        SETTLE_CALCULATED,
        SETTLE_CLAIMED,
        SETTLE_RECOGNIZED,
        SETTLE_PAID,
        SETTLE_DISPUTED,
        SETTLE_REJECTED,
        SETTLE_PARTIALLY_PAID,
    }
)

# Settlement closed — plan condition edits must not silently mutate
SETTLEMENT_CLOSED = frozenset(
    {SETTLE_RECOGNIZED, SETTLE_PAID, SETTLE_PARTIALLY_PAID, SETTLE_REJECTED}
)
