"""Public sales channel constants (anonymous quote → org)."""

from __future__ import annotations

QUOTE_STARTED = "STARTED"
QUOTE_QUOTED = "QUOTED"
QUOTE_PLAN_SELECTED = "PLAN_SELECTED"
QUOTE_CUSTOMER_DATA = "CUSTOMER_DATA"
QUOTE_CHECKOUT_PENDING = "CHECKOUT_PENDING"
QUOTE_PAID = "PAID"
QUOTE_COMPLETED = "COMPLETED"
QUOTE_EXPIRED = "EXPIRED"
QUOTE_ABANDONED = "ABANDONED"

QUOTE_STATUSES: frozenset[str] = frozenset(
    {
        QUOTE_STARTED,
        QUOTE_QUOTED,
        QUOTE_PLAN_SELECTED,
        QUOTE_CUSTOMER_DATA,
        QUOTE_CHECKOUT_PENDING,
        QUOTE_PAID,
        QUOTE_COMPLETED,
        QUOTE_EXPIRED,
        QUOTE_ABANDONED,
    }
)

REGION_US = "US"
REGION_EUROPE = "EUROPE"
REGION_CARIBBEAN = "CARIBBEAN"
REGION_SOUTHAMERICA = "SOUTHAMERICA"
REGION_ASIA = "ASIA"
REGION_OTHER = "OTHER"

DESTINATION_REGIONS: tuple[tuple[str, str], ...] = (
    (REGION_US, "Estados Unidos"),
    (REGION_EUROPE, "Europa"),
    (REGION_CARIBBEAN, "Caribe"),
    (REGION_SOUTHAMERICA, "Sudamérica"),
    (REGION_ASIA, "Asia"),
    (REGION_OTHER, "Otro destino"),
)

REGION_CODES: frozenset[str] = frozenset(c for c, _ in DESTINATION_REGIONS)

PAYMENT_NONE = "NONE"
PAYMENT_PENDING = "PENDING"
PAYMENT_SUCCEEDED = "SUCCEEDED"
PAYMENT_FAILED = "FAILED"
