"""p0_initial_domain

Revision ID: d42e0527b721
Revises: 
Create Date: 2026-08-10 20:07:51.951876
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd42e0527b721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('operational_in_p0', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('external_en1_org_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_en1_org_id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('carriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_carrier_org_code')
    )
    op.create_index(op.f('ix_carriers_organization_id'), 'carriers', ['organization_id'], unique=False)
    op.create_table('commission_split_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('broker_share', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('office_share', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('executive_share', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('referral_share', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_split_rules_organization_id'), 'commission_split_rules', ['organization_id'], unique=False)
    op.create_table('integration_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_organization_id'), 'integration_events', ['organization_id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('party_type', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('trade_name', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('district', sa.String(length=80), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_national_id'), 'parties', ['national_id'], unique=False)
    op.create_index(op.f('ix_parties_organization_id'), 'parties', ['organization_id'], unique=False)
    op.create_table('carrier_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_capabilities_carrier_id'), 'carrier_capabilities', ['carrier_id'], unique=False)
    op.create_table('carrier_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('insurance_line_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['insurance_line_id'], ['insurance_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_products_carrier_id'), 'carrier_products', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_products_insurance_line_id'), 'carrier_products', ['insurance_line_id'], unique=False)
    op.create_table('party_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('party_id', sa.String(length=36), nullable=False),
    sa.Column('role_type', sa.String(length=32), nullable=False),
    sa.Column('context_type', sa.String(length=32), nullable=True),
    sa.Column('context_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('party_id', 'role_type', 'context_type', 'context_id', name='uq_party_role_ctx')
    )
    op.create_index(op.f('ix_party_roles_organization_id'), 'party_roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_party_roles_party_id'), 'party_roles', ['party_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_party_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('insurance_line_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['client_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['insurance_line_id'], ['insurance_lines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_client_party_id'), 'submissions', ['client_party_id'], unique=False)
    op.create_index(op.f('ix_submissions_insurance_line_id'), 'submissions', ['insurance_line_id'], unique=False)
    op.create_index(op.f('ix_submissions_organization_id'), 'submissions', ['organization_id'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=True),
    sa.Column('insurance_line_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_product_id', sa.String(length=36), nullable=True),
    sa.Column('rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('calculation_base', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('agreement_reference', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['carrier_product_id'], ['carrier_products.id'], ),
    sa.ForeignKeyConstraint(['insurance_line_id'], ['insurance_lines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_organization_id'), 'commission_rules', ['organization_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('insurance_line_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_product_id', sa.String(length=36), nullable=True),
    sa.Column('policy_number', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('client_party_id', sa.String(length=36), nullable=False),
    sa.Column('net_premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('annual_premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_effective_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['carrier_product_id'], ['carrier_products.id'], ),
    sa.ForeignKeyConstraint(['client_party_id'], ['parties.id'], ),
    sa.ForeignKeyConstraint(['insurance_line_id'], ['insurance_lines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_carrier_id'), 'policies', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_policies_client_party_id'), 'policies', ['client_party_id'], unique=False)
    op.create_index(op.f('ix_policies_insurance_line_id'), 'policies', ['insurance_line_id'], unique=False)
    op.create_index(op.f('ix_policies_organization_id'), 'policies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=False)
    op.create_index(op.f('ix_policies_submission_id'), 'policies', ['submission_id'], unique=False)
    op.create_table('quote_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('insurance_line_id', sa.String(length=36), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['insurance_line_id'], ['insurance_lines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_requests_organization_id'), 'quote_requests', ['organization_id'], unique=False)
    op.create_table('vehicle_risks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('make', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(length=40), nullable=True),
    sa.Column('vehicle_type', sa.String(length=40), nullable=True),
    sa.Column('usage', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_risks_organization_id'), 'vehicle_risks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vehicle_risks_plate'), 'vehicle_risks', ['plate'], unique=False)
    op.create_index(op.f('ix_vehicle_risks_policy_id'), 'vehicle_risks', ['policy_id'], unique=False)
    op.create_table('carrier_quote_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_request_id', sa.String(length=36), nullable=False),
    sa.Column('carrier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ),
    sa.ForeignKeyConstraint(['quote_request_id'], ['quote_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carrier_quote_requests_carrier_id'), 'carrier_quote_requests', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_quote_requests_quote_request_id'), 'carrier_quote_requests', ['quote_request_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=False),
    sa.Column('calculation_base', sa.String(length=32), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['commission_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_organization_id'), 'commissions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_commissions_policy_id'), 'commissions', ['policy_id'], unique=False)
    op.create_table('payment_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('data_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_policy_id'), 'payments', ['policy_id'], unique=False)
    op.create_table('policy_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('term_source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id')
    )
    op.create_table('renewal_opportunities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('previous_policy_id', sa.String(length=36), nullable=False),
    sa.Column('new_policy_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['new_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['previous_policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewal_opportunities_organization_id'), 'renewal_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_renewal_opportunities_previous_policy_id'), 'renewal_opportunities', ['previous_policy_id'], unique=False)
    op.create_table('commission_splits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('commission_id', sa.String(length=36), nullable=False),
    sa.Column('split_rule_id', sa.String(length=36), nullable=True),
    sa.Column('broker_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('office_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('executive_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referral_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['split_rule_id'], ['commission_split_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_splits_commission_id'), 'commission_splits', ['commission_id'], unique=False)
    op.create_table('installments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_plan_id', sa.String(length=36), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('due_date_source', sa.String(length=32), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_plan_id', 'installment_number', name='uq_installment_num')
    )
    op.create_index(op.f('ix_installments_payment_plan_id'), 'installments', ['payment_plan_id'], unique=False)
    op.create_table('normalized_quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('carrier_quote_request_id', sa.String(length=36), nullable=False),
    sa.Column('premium', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('raw_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_quote_request_id'], ['carrier_quote_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_quotes_carrier_quote_request_id'), 'normalized_quotes', ['carrier_quote_request_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('installment_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['installment_id'], ['installments.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_allocations_installment_id'), 'payment_allocations', ['installment_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_installment_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_normalized_quotes_carrier_quote_request_id'), table_name='normalized_quotes')
    op.drop_table('normalized_quotes')
    op.drop_index(op.f('ix_installments_payment_plan_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_commission_splits_commission_id'), table_name='commission_splits')
    op.drop_table('commission_splits')
    op.drop_index(op.f('ix_renewal_opportunities_previous_policy_id'), table_name='renewal_opportunities')
    op.drop_index(op.f('ix_renewal_opportunities_organization_id'), table_name='renewal_opportunities')
    op.drop_table('renewal_opportunities')
    op.drop_table('policy_terms')
    op.drop_index(op.f('ix_payments_policy_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_commissions_policy_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_organization_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_carrier_quote_requests_quote_request_id'), table_name='carrier_quote_requests')
    op.drop_index(op.f('ix_carrier_quote_requests_carrier_id'), table_name='carrier_quote_requests')
    op.drop_table('carrier_quote_requests')
    op.drop_index(op.f('ix_vehicle_risks_policy_id'), table_name='vehicle_risks')
    op.drop_index(op.f('ix_vehicle_risks_plate'), table_name='vehicle_risks')
    op.drop_index(op.f('ix_vehicle_risks_organization_id'), table_name='vehicle_risks')
    op.drop_table('vehicle_risks')
    op.drop_index(op.f('ix_quote_requests_organization_id'), table_name='quote_requests')
    op.drop_table('quote_requests')
    op.drop_index(op.f('ix_policies_submission_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_organization_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_insurance_line_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_client_party_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_carrier_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_commission_rules_organization_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_submissions_organization_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_insurance_line_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_client_party_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_party_roles_party_id'), table_name='party_roles')
    op.drop_index(op.f('ix_party_roles_organization_id'), table_name='party_roles')
    op.drop_table('party_roles')
    op.drop_index(op.f('ix_carrier_products_insurance_line_id'), table_name='carrier_products')
    op.drop_index(op.f('ix_carrier_products_carrier_id'), table_name='carrier_products')
    op.drop_table('carrier_products')
    op.drop_index(op.f('ix_carrier_capabilities_carrier_id'), table_name='carrier_capabilities')
    op.drop_table('carrier_capabilities')
    op.drop_index(op.f('ix_parties_organization_id'), table_name='parties')
    op.drop_index(op.f('ix_parties_national_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_integration_events_organization_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_commission_split_rules_organization_id'), table_name='commission_split_rules')
    op.drop_table('commission_split_rules')
    op.drop_index(op.f('ix_carriers_organization_id'), table_name='carriers')
    op.drop_table('carriers')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('organizations')
    op.drop_table('insurance_lines')
    # ### end Alembic commands ###
